version: "3"

volumes:
  postgres_data: {}
  postgres_data_backups: {}
  static_volume: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: thumbnails_api_django
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: /start
    volumes:
      - static_volume:/app/static
    ports:
      - "8000:5000"

  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: thumbnails_api_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    env_file:
      - .env

  redis:
    image: redis:6

  celeryworker:
    <<: *django
    image: thumbnails_api_celeryworker
    command: /start-celeryworker
    ports:
      - "8001:8000"

  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    volumes:
      - static_volume:/usr/share/nginx/static
      - ./compose/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - django
