#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py collectstatic --noinput
python manage.py makemigrations
python manage.py migrate
python manage.py load_fixtures

exec /usr/local/bin/gunicorn thumbnails_api.wsgi --bind 0.0.0.0:5000 --chdir=/app