# Generated by Django 4.2.7 on 2024-02-11 14:06

import django.core.validators
from django.db import migrations, models
import thumbnails.models
import thumbnails.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExpiringLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temporary_link",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_in",
                    models.PositiveIntegerField(
                        help_text="Select value from 300 to 30000 (seconds) for expiring link to the original image",
                        validators=[
                            django.core.validators.MinValueValidator(300),
                            django.core.validators.MaxValueValidator(30000),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload an image file (png, jpg, jpeg), max size 5MB",
                        upload_to=thumbnails.models.images_directory_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg"]
                            ),
                            thumbnails.validators.validate_file_size,
                        ],
                    ),
                ),
                ("thumbnails", models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ThumbnailDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        help_text="Enter the width in pixels",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        help_text="Enter the height in pixels",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
            options={
                "unique_together": {("width", "height")},
            },
        ),
    ]
